### ISSUE TITLE
Built in way to get the current language

### ISSUE THREAD

**Issue by Eliran-dev** [martinkr/next-export-i18n-example#1]
Is there a built in function to get the current language? 
Thanks

**Comment by martinkr** [comment]
Hi,

thank you for asking.  The `query` from `useLanguageQuery` should tell you the currently selected language
```javascript
const [query] = useLanguageQuery();
```

If this is not working for you, please open a new issue in the modules repository at https://github.com/martinkr/next-export-i18n - this repository is just a showcase. 

Cheers!
