### ISSUE TITLE
Question: how should static paths be generated?

### ISSUE THREAD

**Issue by christopher-theagen** [martinkr/next-export-i18n-example#5]
Hi- thanks for open-sourcing this!! 

As this example repo does not leverage `getStaticPaths`, I'm left wondering how one could/should configure locale paths to be included in a static export? Is this yet possible with `next-export-i18n` for projects using dynamic routes & `getStaticPaths`?

Said differently, the need is to be able to use `locales` w/in `getStaticPaths`. However, when doing so the following error occurs (running `npx next build`):
```
Collecting page data  ...Error: Invalid locale returned from getStaticPaths for /[[...slug]], the locale en-US is not specified in next.config.js
```

`next.config.js`:
```js
const nextConfig = {
  output: 'export',
  // i18n: { locales, defaultLocale },
  reactStrictMode: true,
  ...
```

Given in the `next.config.js` that `i18n` cannot be specified when `output: 'export'`, how can `locales` be passed in to `getStaticPaths`?

`getStaticPaths` from `./src/pages/[[...slug]].js`:
```js
export const getStaticPaths = async ({ locales = i18n.locales }) => {
  const paths = [];
  await Promise.all(locales?.map(async (locale) => {
    const entries = await fetchNestedFromCache({
      locale,
      contentTypeId: "pageGeneral"
    });
    entries.forEach((entry) => {
      const as = (entry['@as']?.[0] === '/') ? entry['@as'].slice(1) : entry['@as'];
      const slug = (entry.slug === DEFAULT_HOMEPAGE_SLUG) ? [''] : (as || '').split('/');
      if (slug !== 'undefined' && entry.siteTarget.includes("Org")) {
        paths.push({ params: { slug }, locale });
      };
    });
  }));

  return {
    paths,
    fallback: false
  };
};
```

Thanks for reading! Cheers

**Comment by martinkr** [comment]
Hi @christopher-theagen,

Thank you for your contribution. If I understood your question correctly, I don't think it is possible.
_

> Note that Internationalized Routing does not integrate with [output: 'export'](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports) as it does not leverage the Next.js routing layer. Hybrid Next.js applications that do not use output: 'export' are fully supported.
_
https://nextjs.org/docs/pages/building-your-application/routing/internationalization

The [https://github.com/martinkr/next-export-i18n/]( next-export-i18n) provides a purely client-side solution to workoutound the shortcoming of next.js' _i18n_ combined with _output:export_.

Cheers,

Martin

**Comment by christopher-theagen** [comment]
Thanks @martinkr- much obliged!
